version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3333:3333
    command: nodemon server.js
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
