version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  project_api:
    build: ./project_api
    volumes:
      - ./project_api:/usr/src/app
    ports:
      - 5001:5001
    depends_on:
      - db
