version: '3'

services:
  project_api:
    build: ./project_api
    volumes:
      - ./project_api:/usr/src/app
    ports:
      - 5001:5001
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
